"""
Redis Cache Service for RAG Response Caching.

Provides a production-grade caching layer that:
- Caches complete RAG responses by query fingerprint
- Supports TTL-based automatic expiry
- Handles cache invalidation on project re-indexing
- Tracks hit/miss rates for analytics
- Degrades gracefully when Redis is unavailable

Cache key structure:
    rag:cache:{sha256(query+project_id+prompt_type+model+top_k)}
    rag:stats:hits     — atomic counter
    rag:stats:misses   — atomic counter
    rag:project:{id}:keys — set of all cache keys for a project
"""

from __future__ import annotations

import hashlib
import json
import logging
import time
from typing import Any, Optional

import redis.asyncio as aioredis

from app.config import settings

logger = logging.getLogger(__name__)

# Default TTL: 1 hour for cached responses
DEFAULT_CACHE_TTL: int = getattr(settings, "RAG_CACHE_TTL", 3600)
# Maximum TTL: 24 hours
MAX_CACHE_TTL: int = 86400
# Cache key prefix
CACHE_PREFIX: str = "rag:cache:"
# Stats keys
STATS_HITS_KEY: str = "rag:stats:hits"
STATS_MISSES_KEY: str = "rag:stats:misses"
# Project key set prefix (for invalidation)
PROJECT_KEYS_PREFIX: str = "rag:project:"


def make_cache_key(
    query: str,
    project_id: str,
    prompt_type: str = "code_qa",
    model: str = "tinyllama",
    top_k: int = 8,
) -> str:
    """
    Generate a deterministic cache key for a RAG request.

    Two requests produce the same key if and only if they have
    identical: query, project_id, prompt_type, model, and top_k.

    Args:
        query: User's question text
        project_id: Project UUID string
        prompt_type: Prompt type enum value
        model: LLM model name
        top_k: Number of chunks retrieved

    Returns:
        Cache key string like "rag:cache:abc123def456..."
    """
    fingerprint = f"{query.strip().lower()}::{project_id}::{prompt_type}::{model}::{top_k}"
    hash_hex = hashlib.sha256(fingerprint.encode("utf-8")).hexdigest()
    return f"{CACHE_PREFIX}{hash_hex}"


class CacheService:
    """
    Redis-backed cache for RAG responses with analytics and invalidation.

    Wraps redis.asyncio with error handling so the application
    continues working (uncached) if Redis is temporarily unavailable.

    Usage:
        cache = CacheService()
        await cache.connect()

        # Try cache first
        cached = await cache.get_cached_response(key)
        if cached:
            return cached

        # Compute response...
        await cache.set_cached_response(key, response_dict, project_id)
    """

    def __init__(self) -> None:
        """Initialize with Redis URL from settings."""
        self._redis: Optional[aioredis.Redis] = None
        self._redis_url: str = settings.REDIS_URL
        self._connected: bool = False
        logger.info("CacheService initialized (url=%s)", self._redis_url[:30])

    @property
    def is_connected(self) -> bool:
        """Whether Redis connection is active."""
        return self._connected and self._redis is not None

    async def connect(self) -> bool:
        """
        Establish Redis connection.

        Returns True if connected, False if Redis is unavailable.
        Never raises — always fails gracefully.
        """
        try:
            self._redis = aioredis.from_url(
                self._redis_url,
                decode_responses=True,
                socket_connect_timeout=5,
                retry_on_timeout=True,
            )
            # Verify connection with PING
            await self._redis.ping()
            self._connected = True
            logger.info("Redis cache connected")
            return True
        except Exception as exc:
            logger.warning("Redis connection failed (caching disabled): %s", exc)
            self._redis = None
            self._connected = False
            return False

    async def disconnect(self) -> None:
        """Close Redis connection gracefully."""
        if self._redis:
            try:
                await self._redis.close()
            except Exception:
                pass
            self._redis = None
            self._connected = False
            logger.info("Redis cache disconnected")

    async def get_cached_response(
        self, cache_key: str
    ) -> Optional[dict[str, Any]]:
        """
        Retrieve a cached RAG response.

        Increments hit/miss counters for analytics.

        Args:
            cache_key: Key generated by make_cache_key()

        Returns:
            Cached response dict if found, None on miss or error
        """
        if not self.is_connected:
            return None

        try:
            start = time.perf_counter()
            cached_json = await self._redis.get(cache_key)
            elapsed_ms = (time.perf_counter() - start) * 1000

            if cached_json:
                # Cache HIT
                data = json.loads(cached_json)
                data["cached"] = True
                data["cache_elapsed_ms"] = round(elapsed_ms, 2)
                await self._redis.incr(STATS_HITS_KEY)
                logger.debug("Cache HIT: %s (%.1fms)", cache_key[:30], elapsed_ms)
                return data
            else:
                # Cache MISS
                await self._redis.incr(STATS_MISSES_KEY)
                logger.debug("Cache MISS: %s", cache_key[:30])
                return None

        except Exception as exc:
            logger.warning("Cache read failed: %s", exc)
            return None

    async def set_cached_response(
        self,
        cache_key: str,
        response_data: dict[str, Any],
        project_id: Optional[str] = None,
        ttl: int = DEFAULT_CACHE_TTL,
    ) -> bool:
        """
        Store a RAG response in cache with TTL.

        Also tracks the key in a per-project set for targeted
        invalidation when the project is re-indexed.

        Args:
            cache_key: Key generated by make_cache_key()
            response_data: Complete response dict to cache
            project_id: Optional project ID for invalidation tracking
            ttl: Time-to-live in seconds (default 1 hour)

        Returns:
            True if cached successfully, False on error
        """
        if not self.is_connected:
            return False

        try:
            ttl = min(ttl, MAX_CACHE_TTL)
            serialized = json.dumps(response_data, default=str)

            await self._redis.setex(cache_key, ttl, serialized)

            # Track key in project set for bulk invalidation
            if project_id:
                project_set_key = f"{PROJECT_KEYS_PREFIX}{project_id}:keys"
                await self._redis.sadd(project_set_key, cache_key)
                await self._redis.expire(project_set_key, MAX_CACHE_TTL)

            logger.debug("Cache SET: %s (ttl=%ds)", cache_key[:30], ttl)
            return True

        except Exception as exc:
            logger.warning("Cache write failed: %s", exc)
            return False

    async def invalidate_project_cache(
        self, project_id: str
    ) -> int:
        """
        Invalidate all cached responses for a project.

        Called when a project's codebase is re-indexed, making
        all existing cached responses potentially stale.

        Args:
            project_id: Project UUID string

        Returns:
            Number of cache entries invalidated
        """
        if not self.is_connected:
            return 0

        try:
            project_set_key = f"{PROJECT_KEYS_PREFIX}{project_id}:keys"
            cached_keys = await self._redis.smembers(project_set_key)

            if not cached_keys:
                return 0

            # Delete all cached responses for this project
            pipeline = self._redis.pipeline()
            for key in cached_keys:
                pipeline.delete(key)
            pipeline.delete(project_set_key)
            await pipeline.execute()

            count = len(cached_keys)
            logger.info(
                "Invalidated %d cached responses for project %s",
                count, project_id,
            )
            return count

        except Exception as exc:
            logger.warning("Cache invalidation failed: %s", exc)
            return 0

    async def invalidate_key(self, cache_key: str) -> bool:
        """
        Invalidate a single cache entry.

        Args:
            cache_key: Key to delete

        Returns:
            True if deleted, False if not found or error
        """
        if not self.is_connected:
            return False

        try:
            result = await self._redis.delete(cache_key)
            return result > 0
        except Exception as exc:
            logger.warning("Cache key deletion failed: %s", exc)
            return False

    async def get_cache_stats(self) -> dict[str, Any]:
        """
        Get cache performance statistics.

        Returns:
            Dict with hits, misses, hit rate, and Redis info
        """
        if not self.is_connected:
            return {
                "connected": False,
                "hits": 0,
                "misses": 0,
                "hit_rate": 0.0,
            }

        try:
            pipeline = self._redis.pipeline()
            pipeline.get(STATS_HITS_KEY)
            pipeline.get(STATS_MISSES_KEY)
            pipeline.dbsize()
            results = await pipeline.execute()

            hits = int(results[0] or 0)
            misses = int(results[1] or 0)
            total = hits + misses
            db_size = int(results[2] or 0)

            return {
                "connected": True,
                "hits": hits,
                "misses": misses,
                "total_requests": total,
                "hit_rate": round(hits / total, 3) if total > 0 else 0.0,
                "total_keys_in_db": db_size,
            }

        except Exception as exc:
            logger.warning("Failed to get cache stats: %s", exc)
            return {"connected": True, "error": str(exc)}

    async def clear_all(self) -> int:
        """
        Clear ALL rag:cache: keys (for testing/reset only).

        Returns:
            Number of keys deleted
        """
        if not self.is_connected:
            return 0

        try:
            cursor = b"0"
            total = 0
            while cursor:
                cursor, keys = await self._redis.scan(
                    cursor=cursor, match=f"{CACHE_PREFIX}*", count=100
                )
                if keys:
                    await self._redis.delete(*keys)
                    total += len(keys)
                if cursor == b"0" or cursor == 0:
                    break
            logger.info("Cleared %d cache entries", total)
            return total
        except Exception as exc:
            logger.warning("Cache clear failed: %s", exc)
            return 0


# ── Global Singleton ──────────────────────────────────────────────
cache_service = CacheService()


# ================================================================
# Compatibility shims — imported by health.py and other modules
# ================================================================

async def get_redis() -> Optional[aioredis.Redis]:
    """
    Get the active Redis client instance.

    Returns None if Redis is not connected.
    Used as a FastAPI dependency: redis = Depends(get_redis)
    """
    if cache_service.is_connected and cache_service._redis is not None:
        return cache_service._redis

    # Try to connect if not already connected
    connected = await cache_service.connect()
    if connected:
        return cache_service._redis
    return None


class RedisHealthMonitor:
    """
    Redis health monitoring utility.

    Provides health check methods used by the /health/redis endpoint.
    Wraps the CacheService singleton.
    """

    @staticmethod
    async def ping() -> bool:
        """Ping Redis to verify connectivity."""
        if not cache_service.is_connected:
            await cache_service.connect()
        if not cache_service.is_connected:
            return False
        try:
            await cache_service._redis.ping()
            return True
        except Exception:
            return False

    @staticmethod
    async def get_info() -> dict:
        """Get Redis server info for health endpoint."""
        if not cache_service.is_connected:
            return {"status": "disconnected"}
        try:
            stats = await cache_service.get_cache_stats()
            return {"status": "connected", **stats}
        except Exception as exc:
            return {"status": "error", "detail": str(exc)}