"""initial_schema

Revision ID: b75998feb73f
Revises: 
Create Date: 2026-07-24 16:27:17.400061+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers used by Alembic
revision: str = 'b75998feb73f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — creates or modifies database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address used for login'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique display name'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account enabled/disabled flag'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verification status'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Admin privilege flag'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='User full name'),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment='Profile picture URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Short user biography'),
    sa.Column('preferred_model', sa.String(length=100), nullable=False, comment='Preferred Ollama model name'),
    sa.Column('theme', sa.String(length=20), nullable=False, comment='UI theme preference: dark or light'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Most recent successful login'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='User who owns this project'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Project display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional project description'),
    sa.Column('repo_url', sa.String(length=500), nullable=True, comment='Optional GitHub or GitLab repository URL'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | uploading | indexing | ready | error'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if status is error'),
    sa.Column('index_progress', sa.Float(), nullable=False, comment='Indexing progress percentage 0.0 to 100.0'),
    sa.Column('primary_language', sa.String(length=100), nullable=True, comment='Primary detected programming language'),
    sa.Column('language_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON map of language to percentage, e.g. {python: 80, js: 20}'),
    sa.Column('total_files', sa.Integer(), nullable=False, comment='Total number of indexed files'),
    sa.Column('total_lines', sa.BigInteger(), nullable=False, comment='Total lines of code across all files'),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False, comment='Total size of all files in bytes'),
    sa.Column('chroma_collection_name', sa.String(length=255), nullable=True, comment='ChromaDB collection name storing embeddings for this project'),
    sa.Column('embedding_count', sa.Integer(), nullable=False, comment='Number of embedding chunks stored in ChromaDB'),
    sa.Column('avg_complexity', sa.Float(), nullable=True, comment='Average cyclomatic complexity across all files'),
    sa.Column('complexity_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full complexity analysis report as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True, comment='When indexing last completed successfully'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_collection_name')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Auto-generated or user-set session title'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False when session is archived'),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Ollama model used for this session'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='Total messages in this session'),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False, comment='Cumulative token count for cost tracking'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent message'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_project_id'), 'chat_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project this file belongs to'),
    sa.Column('file_path', sa.String(length=1000), nullable=False, comment='Relative path within the project, e.g. src/utils/helpers.py'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='File name only, e.g. helpers.py'),
    sa.Column('file_extension', sa.String(length=50), nullable=True, comment='File extension e.g. .py .js .ts'),
    sa.Column('language', sa.String(length=100), nullable=True, comment='Detected programming language'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME type of the file'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('line_count', sa.Integer(), nullable=False, comment='Total number of lines in the file'),
    sa.Column('content', sa.Text(), nullable=True, comment='Full file content as UTF-8 text'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA256 hash of file content for deduplication'),
    sa.Column('encoding', sa.String(length=50), nullable=False, comment='Character encoding detected by chardet'),
    sa.Column('is_parsed', sa.Boolean(), nullable=False, comment='True when Tree-sitter parsing is complete'),
    sa.Column('is_embedded', sa.Boolean(), nullable=False, comment='True when embeddings are stored in ChromaDB'),
    sa.Column('is_binary', sa.Boolean(), nullable=False, comment='True if file is binary and cannot be parsed as text'),
    sa.Column('parse_error', sa.Text(), nullable=True, comment='Error message if parsing failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='Number of embedding chunks created from this file'),
    sa.Column('functions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of function names extracted by Tree-sitter'),
    sa.Column('classes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of class names extracted by Tree-sitter'),
    sa.Column('imports', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of import statements extracted by Tree-sitter'),
    sa.Column('complexity_score', sa.Float(), nullable=True, comment='Cyclomatic complexity score for this file'),
    sa.Column('ast_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional AST analysis metadata from Tree-sitter'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True, comment='When Tree-sitter parsing completed'),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True, comment='When ChromaDB embedding completed'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_id'), 'project_files', ['id'], unique=False)
    op.create_index(op.f('ix_project_files_language'), 'project_files', ['language'], unique=False)
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who triggered this task'),
    sa.Column('task_type', sa.String(length=100), nullable=False, comment='indexing | bug_scan | doc_gen | test_gen | security | refactor | perf_analysis'),
    sa.Column('task_name', sa.String(length=255), nullable=True, comment='Human-readable task name shown in UI'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='Celery task UUID for querying task state'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | running | completed | failed | cancelled'),
    sa.Column('progress', sa.Float(), nullable=False, comment='Task completion percentage 0.0 to 100.0'),
    sa.Column('status_message', sa.String(length=500), nullable=True, comment='Current status detail shown in UI progress display'),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Input parameters passed to the task'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Task result payload — agent report, analysis, etc.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Full error message if status is failed'),
    sa.Column('error_traceback', sa.Text(), nullable=True, comment='Python traceback for debugging failed tasks'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When Celery worker picked up this task'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the task finished (success or failure)'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='user | assistant | system'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full message text content'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='Model that generated this message (assistant only)'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='Input token count'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='Output token count'),
    sa.Column('generation_time_ms', sa.Float(), nullable=True, comment='Time taken to generate this message in milliseconds'),
    sa.Column('rag_context_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of code chunk IDs retrieved from ChromaDB for this message'),
    sa.Column('rag_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Source file paths used as RAG context'),
    sa.Column('rag_similarity_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Similarity scores for retrieved chunks'),
    sa.Column('is_streaming', sa.Boolean(), nullable=False, comment='True while the AI is still generating this message'),
    sa.Column('is_error', sa.Boolean(), nullable=False, comment='True if message generation failed'),
    sa.Column('error_detail', sa.Text(), nullable=True, comment='Error details if is_error is True'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When streaming generation completed'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration — restores previous database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_celery_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_language'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_project_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
